

1.   Syed Muhammad Oaun
2.   i212702 (BS-AI-J)



In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:

class LinearRegression:
    def __init__(self, learning_rate=0.01, max_iterations=1000, tolerance=1e-4, print_interval=10):
        self.learning_rate = learning_rate
        self.max_iterations = max_iterations
        self.tolerance = tolerance
        self.print_interval = print_interval
        self.theta = None

    def hypothesis(self, X):
        X = np.hstack((X, np.ones((X.shape[0], 1))))
        return np.dot(X, self.theta.reshape(-1, 1))

    def der_cost_function(self, X, y):
        h = self.hypothesis(X)
        y = y.reshape(-1, 1)
        #print(h.shape)
        #print(y.shape)
        #print((y-h).shape)
        #print(X.shape)
        X = np.hstack((X, np.ones((X.shape[0], 1))))
        return -2 * np.mean((y - h) * X, axis=0)

    def cost_function(self, X, y):
        h = self.hypothesis(X)
        y = y.reshape(-1, 1)
        #print(y.shape)
        #print(h.shape)
        #print((y-h).shape)
        return np.mean((y - h) ** 2)

    def gradient_descent(self, X, y):
        der = self.der_cost_function(X, y)
        #print("der",der.shape)
        self.theta = self.theta - self.learning_rate * der

    def get_weights(self):
        return self.theta

    def fit(self, X, y):

        num_features = X.shape[1]
        self.theta = np.zeros(num_features + 1)

        for iteration in range(1, self.max_iterations + 1):
            prev_theta = np.copy(self.theta)
            self.gradient_descent(X, y)

            if iteration % self.print_interval == 0 or iteration == 1 :
                loss = self.cost_function(X, y)
                print(f"Iteration {iteration}, Loss: {loss}")
                print(f"weights ", self.theta)

            if np.linalg.norm(self.theta - prev_theta) < self.tolerance:
                print(f"Converged at iteration {iteration}")
                break

    def predict(self, X):
        return self.hypothesis(X).flatten()




In [3]:
path = 'E:/FAST_NUCES/SEMISTER_6_BS(AI)/ANN/ASSIGNMNETS/ENB2012_data.csv'
data = pd.read_csv(path)

# Select relevant features and target (Y1: Heating Load)
X = data.iloc[:, :-2].to_numpy()
y = data.iloc[:, -2].to_numpy()

In [4]:
X.shape

(768, 8)

In [5]:
y[:5]

array([15.55, 15.55, 15.55, 15.55, 20.84])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=42)   # test size very low to just get a few examples for testing 

In [13]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

linear_reg = LinearRegression(learning_rate=0.01, max_iterations=5000, tolerance=1e-4, print_interval=500)
linear_reg.fit(X_train_scaled, y_train)

weights = linear_reg.get_weights()
print("Model Weights:", weights)


Iteration 1, Loss: 568.2848447839291
weights  [ 0.12578947 -0.13297543  0.09280267 -0.17427496  0.17968286 -0.00066967
  0.05428881  0.01727534  0.44564947]
Iteration 500, Loss: 9.809715997165112
weights  [-0.62622319 -1.13184715  2.58316886 -2.35363445  5.3142247  -0.05130146
  2.64485804  0.31048882 22.28155957]
Iteration 1000, Loss: 9.061326855477095
weights  [-1.73435269 -1.13564973  2.0084518  -2.07842356  6.73847625 -0.04730878
  2.64386899  0.31284594 22.28247365]
Iteration 1500, Loss: 8.790611741551603
weights  [-2.45353016 -1.18452055  1.65934878 -1.95650344  7.55655983 -0.04489491
  2.64300778  0.31448961 22.28247368]
Iteration 2000, Loss: 8.688683289761077
weights  [-2.93921233 -1.25807462  1.44447396 -1.92371301  8.01617554 -0.04342421
  2.64247721  0.31546471 22.28247368]
Iteration 2500, Loss: 8.646746331869076
weights  [-3.28375417 -1.3443095   1.30958233 -1.94206236  8.26423739 -0.04251481
  2.64214378  0.31604303 22.28247368]
Iteration 3000, Loss: 8.626451018594347
weig

In [14]:
X_test_scaled = scaler.transform(X_test)
predictions = linear_reg.predict(X_test_scaled)
print(X_test.shape)

(8, 8)


In [18]:
X_test_scaled[1]

array([-9.86881060e-01,  9.98644591e-01,  7.36913673e-04,  9.70221970e-01,
       -9.97371875e-01, -1.35254030e+00,  1.19980603e-01, -1.16568111e+00])

In [19]:
predictions[1]

14.050411684848058

In [20]:
y_test[1]

13.17

In [21]:
linear_reg.theta

array([-4.19898006, -1.80050976,  1.06824301, -2.26832152,  8.40304594,
       -0.0409923 ,  2.6415445 ,  0.31682295, 22.28247368])